# Generated by Django 5.0.6 on 2026-07-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='annual_price_cop',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway_customer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway_subscription_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='overage_amount_cop',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='overage_conversations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='spend_ceiling_cop',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], default='trialing', max_length=20),
        ),
    ]
