# Generated by Django 5.0.6 on 2026-07-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_reconsolidate_learning_purposes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbarticle',
            name='purpose',
            field=models.CharField(blank=True, choices=[('faq', 'Preguntas frecuentes'), ('business', 'Sobre el negocio'), ('sales_scripts', 'Scripts de venta'), ('policy', 'Políticas del negocio')], default='faq', max_length=30),
        ),
    ]
