# Generated by Django 5.0.6 on 2026-07-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_learning_candidate_conversation_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentextractioncandidate',
            name='kind',
            field=models.CharField(choices=[('service', 'Service'), ('pricing_rule', 'Pricing rule'), ('policy', 'Policy'), ('flow_hint', 'Flow hint'), ('ai_summary', 'AI Summary'), ('ai_qa', 'AI Q&A')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='learningcandidate',
            name='kind',
            field=models.CharField(choices=[('faq', 'FAQ'), ('conversation_example', 'Conversation example'), ('winning_reply', 'Winning reply'), ('objection', 'Objection'), ('estilo_comunicacion', 'Estilo de comunicación')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='metricssnapshot',
            name='conversations_with_order',
            field=models.IntegerField(default=0),
        ),
    ]
