# Generated by Django 5.0.6 on 2026-07-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0009_contact_memory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salessession',
            new_name='sales_sessi_organiz_c6e66d_idx',
            old_name='sales_sessi_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='salessession',
            new_name='sales_sessi_organiz_d16dce_idx',
            old_name='sales_sessi_organiz_2_idx',
        ),
        migrations.RenameIndex(
            model_name='salessession',
            new_name='sales_sessi_convers_4c8fac_idx',
            old_name='sales_sessi_conversa_idx',
        ),
    ]
