# Generated by Django 5.0.6 on 2026-07-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_order_conversation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='made_to_order',
            field=models.BooleanField(default=False, help_text='Custom/handmade per order rather than sold from fixed stock (e.g. personalized jewelry).'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_size',
            field=models.BooleanField(default=False, help_text='Needs a size/measurement from the customer before it can be confirmed (rings, clothing with fixed sizing, etc.)'),
        ),
    ]
